name: Create and publish a Docker image
on:
  push:
    branches:
      - lw-0.*

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push-image:
    name: >-
      Build and push, dd: ${{ matrix.datadog }}

    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        datadog: [true, false]

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup Git metadata
        id: git-meta
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          # ensure we're always taking upstream tags into account to calculate distance
          upstream="$(gh repo view "${{ github.repository }}" --json parent --jq '.parent.owner.login + "/" + .parent.name')"
          git remote add upstream "https://github.com/$upstream.git"
          git fetch upstream --tags
          echo "git-version=$(git describe --tags)" >> "$GITHUB_OUTPUT"

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=raw,value=${{ steps.git-meta.outputs.git-version }},suffix=${{ fromJSON(matrix.datadog) && '-dd' || '' }}
            type=sha,format=long,suffix=${{ fromJSON(matrix.datadog) && '-dd' || '' }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: >-
            ${{ fromJSON(matrix.datadog) && 'dd.' || '' }}Dockerfile
          build-args: |
            DD_VERSION=${{ steps.git-meta.outputs.git-version }}
            DD_GIT_REPOSITORY_URL=${{ github.server_url }}/${{ github.repository }}
            DD_GIT_COMMIT_SHA=${{ github.sha }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: |
            ${{ steps.meta.outputs.labels }}
            com.datadoghq.tags.service=${{ github.event.repository.name }}
            com.datadoghq.tags.version=${{ steps.git-meta.outputs.git-version }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
