name: Create and publish a Docker image
on:
  push:
    branches:
      - lw-0.*
env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}/${{ github.ref_name }}
jobs:
  build-and-push-image:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    strategy:
      matrix:
        datadog: [true, false]

    steps:
      - name: Get short commit hash
        id: short-sha
        run: |
          echo "sha-7=$(cut -c 1-7 <<< "$GITHUB_SHA")" >> "$GITHUB_OUTPUT"

      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: >-
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}${{
              fromJSON(matrix.datadog) && '-dd' || ''
            }}
          tags: |
            type=sha,format=long

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.repository_owner }}
          password: ${{ github.token }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: >-
            ${{ fromJSON(matrix.datadog) && 'dd.' || '' }}Dockerfile
          build-args: |
            DD_VERSION=${{ github.ref_name }}-${{ steps.short-sha.outputs.sha-7 }}
            DD_GIT_REPOSITORY_URL=${{ github.server_url }}/${{ github.repository }}
            DD_GIT_COMMIT_SHA=${{ github.sha }}
          platforms: linux/amd64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
